yoti.settings:
  type: config_object
  label: 'Yoti Settings'
  mapping:
    yoti_app_id:
      type: string
      label: 'App ID'
    yoti_scenario_id:
      type: string
      label: 'Scenario ID'
    yoti_sdk_id:
      type: string
      label: 'SDK ID'
    yoti_success_url:
      type: string
      label: 'Success URL'
    yoti_fail_url:
      type: string
      label: 'Fail URL'
    yoti_pem:
      type: sequence
      label: 'PEM File'
      sequence:
        type: string
        label: 'fid'
    yoti_age_verification:
      type: integer
      label: 'Prevent users who have not passed age verification to access your site'
    yoti_only_existing:
      type: integer
      label: 'Only allow existing Drupal users to link their Yoti account'
    yoti_user_email:
      type: integer
      label: 'Attempt to link Yoti email address with Drupal account for first time users'
    yoti_company_name:
      type: string
      label: 'Company name'
