<?php

namespace Drupal\yoti_connect\Form;

use Drupal\Core\Form\FormStateInterface;
use Drupal\user\Form\UserLoginForm;

class YotiConnectUserLoginForm extends UserLoginForm
{
    public function buildForm(array $form, FormStateInterface $form_state)
    {
        $form = parent::buildForm($form, $form_state);

        $form['yoti_nolink'] = array(
            '#weight' => -1000,
            '#type' => 'inline_template',
            '#template' => '{{ somecontent | raw }}',
            '#default_value' => \Drupal::config('yoti_nolink')->get(),
            '#context' => [
                'somecontent' => '<div class="form-item form-type-checkbox form-item-yoti-link messages warning" style="margin: 0 0 15px 0">
                    <div><b>Warning: You are about to link Drupal to your Yoti account. Click the box below to keep them separate.</b></div>
                    <input type="checkbox" id="edit-yoti-link" name="yoti_nolink" value="1" class="form-checkbox"' . (!empty($form_state->get('yoti_nolink')) ? ' checked="checked"' : '') . '>
                    <label class="option" for="edit-yoti-link">Don\'t link my Yoti account</label>
                </div>',
            ],
        );

        return $form;
    }

    /**
     * @param array $form
     * @param \Drupal\Core\Form\FormStateInterface $form_state
     */
    public function submitForm(array &$form, FormStateInterface $form_state)
    {
        $_SESSION['yoti_nolink'] = $form_state->get('yoti_nolink');
        parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
    }
}